import { Card, Page } from "@/components/ui";

export const dynamic = "force-static";

export const metadata = {
  title: "Terms — Farm Tracker",
  description: "Terms of use for Farm Tracker.",
};

/**
 * Terms of use, public and unauthenticated, for the same reason as the privacy
 * policy: Google asks for one before an external app can leave Testing.
 */
export default function TermsPage() {
  return (
    <Page title="Terms of use" subtitle="Last updated 30 August 2026">
      <Card>
        <div className="space-y-4">
          <p>
            Farm Tracker is a private application built for one family farm in
            Silang, Cavite. It is not a product, it is not sold, and it is not
            open to the public.
          </p>

          <h2 className="text-lg font-bold">Who may use it</h2>
          <p>
            Only the people the farm&apos;s owners have added to the access list.
            Anyone else who signs in will be refused.
          </p>

          <h2 className="text-lg font-bold">What it is for</h2>
          <p>
            Recording the farm&apos;s costs, harvests, sales, measurements, tasks
            and photographs, and keeping a copy of those records in the
            owners&apos; own Google Drive.
          </p>

          <h2 className="text-lg font-bold">No warranty</h2>
          <p>
            The app is provided as it is, with no guarantee of availability or
            accuracy. Figures it reports are only as good as what has been entered
            into it. Farming decisions remain the owners&apos; own, and
            suggestions produced by the app — including anything generated by
            Claude — are advice to weigh, never instructions to follow. Nothing in
            the app is professional agronomic advice.
          </p>

          <h2 className="text-lg font-bold">Ending use</h2>
          <p>
            The owners may stop using the app at any time. Records held in Google
            Drive stay in their Google account and remain readable without it.
          </p>

          <h2 className="text-lg font-bold">Contact</h2>
          <p>
            <a
              href="mailto:jamie.bawalan@gmail.com"
              className="font-semibold text-brand underline underline-offset-4"
            >
              jamie.bawalan@gmail.com
            </a>
          </p>
        </div>
      </Card>
    </Page>
  );
}
